server.address=127.0.0.1
server.port=${PORT:8081}
management.endpoints.web.exposure.include=health
spring.application.name=deepwater
spring.datasource.url=${DB_URL:jdbc:h2:file:./data/deepwater;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE}
spring.datasource.username=${DB_USER:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8
spring.graphql.graphiql.enabled=true
deepwater.teacher.email=${DEEPWATER_TEACHER_EMAIL:}
